### ISSUE TITLE
error message "Type annotations can only be used in TypeScript files"

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-type-checker-vscode#5]
What do I need to do to prevent this error in VS Code?
Here is a simple `App.svelte` file that demonstrates this.
It complains about all the `: number` type annotations.
I have the extensions "Svelte Beta" and "Svelte Type Checker" installed and have restarted VS Code.

```html
<script lang="typescript">
  function add(n1: number, n2: number): number {
    return n1 + n2;
  }

  const sum = add(1, '2');
</script>

<main>
  <div>sum in ts = {sum}</div>
  <div>sum in HTML = {add(1, '2')}</div>
</main>
```

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)

**Comment by halfnelson** [comment]
just tried this and it seems to be working as expected.
I have vscode extensions "Svelte Beta" and "Svelte Type Checker" installed.
I created a svelte project from template,
I `npm install --save-dev svelte-preprocess`

I added svelte.config.js to root folder (one level above src)
it contains
```js
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess(),
};
```
then in vscode I go to command palette and search for svelte, and run the `Svelte: restart language server` command

![TS_screenshot](https://user-images.githubusercontent.com/551284/80104057-736a1f00-85b9-11ea-9637-25b6cfccf05c.png)
